### ISSUE TITLE
Sidebar instead of dropdown menu

### ISSUE THREAD

**Issue by TaylanTatli** [LinArcX/giti#1]
Is it possible? It's too hard to use like this.

**Comment by LinArcX** [comment]
Hello. Thanks for suggestion. Yes. I think It's a better idea to implement projects part as tree view in SIDEBAR. TBH I don't have enough time to implement it. 

But pull request are always welcome.

**Comment by TaylanTatli** [comment]
I wish i know how to do it. :disappointed:
